# Generated by Django 3.1.5 on 2021-01-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='userId',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
